### ISSUE TITLE
`getSelectedNodes` doesn't return anything

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cyjShiny#10]
Is it supposed to return a list of node IDs?

**Comment by paul-shannon** [comment]
Fixed:  a list of node IDs is returned and, in tinyApp.R (which needs a better name), displayed.
Better than returning only a simple list would be a data.frame.   
A worthwhile option:  optionally emit ````Shiny.setInputValue```` with every javascript selectionion event, so that R can display a data.frame, or list, of the current selection, without requiring an explicit press of the ````Get Selected Nodes```` button.
