### ISSUE TITLE
Breaks datatable

### ISSUE THREAD

**Issue by CosteaPaul** [cytoscape/cyjShiny#13]
Trying to use cyjShiny and DT in the same app, but after adding cyjShiny, DT stops working.
I get a js error saying DataTable is not a function. 

This only happens if "cyjShinyOutput('cyjShiny')" is in the UI. Comment that out, and everything is fine! So....something going on with that div?

Since i imagine a lot of people who would like to use cyj use DT a lot, i'm filing this as an issue here... hope that's ok.

**Comment by paul-shannon** [comment]
@CosteaPaul  - Thanks for the bug report.   I was able to reproduce it.  

Do you see this error message in your javascript console?
````
Uncaught TypeError: $table.DataTable is not a function
    at Object.renderValue (datatables.js:286)
    at exports.OutputBinding.shinyBinding.renderValue (htmlwidgets.js:516)
    at exports.OutputBinding.onValueChange (shiny.min.js:4)
````
That ````DataTable```` is not defined may be caused by cyjShiny having jQuery loaded twice: once in my package.json, once in Shiny.   This stackoverflow [post](https://stackoverflow.com/questions/31227844/typeerror-datatable-is-not-a-function) suggests as much.  

I hope to figure this out quickly.  I will keep you posted.  

Thanks again for the bug report.  (Please let me know if the error I see is also what you see.)

**Comment by paul-shannon** [comment]
@CosteaPaul - I think I have this fixed.    Adding a call to ````jQuery.noConflict()```` at the top of cyjShiny.js seems to be all that is needed.

Committed in version 0.99.27 of the package, just now.
Let me know if this solves your problem.  
A sample shinyApp with cyjShiny and DT: [inst/examples/withDT/app.R](https://raw.githubusercontent.com/cytoscape/cyjShiny/master/inst/examples/withDT/app.R)

Does this solve your problem?

**Comment by CosteaPaul** [comment]
Indeed, this is now fixed. Thanks!
